project:
  type: website
  output-dir: docs

website:
  title: "zool710-intro-ke-cao"
  navbar:
    background: purple
    foreground: white
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



